baseURL = "https://briarproject.org/manual"
languageCode = "en"
DefaultContentLanguage = "en"
canonifyURLs = "true"
theme = "briar-manual"

[languages]
  [languages.de]
    languageName = "Deutsch"
  [languages.en]
    languageName = "English"
  [languages.es]
    languageName = "español"
  [languages.fa]
    languageName = "فارسى"
    languagedirection = "rtl"
  [languages.fr]
    languageName = "français"
  [languages.gl]
    languageName = "galego"
  [languages.hu]
    languageName = "magyar"
  [languages.is]
    languageName = "íslenska"
  [languages.ka]
    languageName = "ქართული"
  [languages.it]
    languageName = "italiano"
  [languages.lt]
    languageName = "lietuvių"
  [languages.my]
    languageName = "မြန်မာ"
  [languages.nb-no]
    languageName = "norsk bokmål"
  [languages.nl]
    languageName = "Nederlands"
  [languages.ro]
    languageName = "română"
  [languages.ru]
    languageName = "русский"
  [languages.pl]
    languageName = "polski"
  [languages.sq]
    languageName = "shqip"
  [languages.sv]
    languageName = "svenska"
  [languages.tr]
    languageName = "Türkçe"
  [languages.uk]
    languageName = "украї́нська мо́ва"
  [languages.zh-hans]
    languageName = "简化字"
