baseURL = "https://briarproject.org/manual"
languageCode = "en"
DefaultContentLanguage = "en"
canonifyURLs = "true"
theme = "briar-manual"

[languages]
  [languages.de]
    languageName = "German"
  [languages.en]
    languageName = "English"
  [languages.es]
    languageName = "español"
  [languages.fa]
    languageName = "فارسى"
    languagedirection = "rtl"
  [languages.fr]
    languageName = "français"
  [languages.gl]
    languageName = "galego"
  [languages.is]
    languageName = "íslenska"
  [languages.it]
    languageName = "italiano"
  [languages.lt]
    languageName = "lietuvių"
  [languages.ru]
    languageName = "русский"
  [languages.sq]
    languageName = "shqip"
  [languages.sv]
    languageName = "svenska"
  [languages.tr]
    languageName = "Türkçe"
  [languages.zh-hans]
    languageName = "简化字"
