baseURL = "https://briarproject.org/manual"
languageCode = "en"
DefaultContentLanguage = "en"
canonifyURLs = "true"
theme = "briar-manual"

[languages]
  [languages.en]
    languageName = "English"
  [languages.es]
    languageName = "español"
  [languages.fr]
    languageName = "français"
  [languages.fa]
    languageName = "فارسى"
    languagedirection = "rtl"
